#index:
#    path: /
#    controller: App\Controller\DefaultController::index

meteo:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template : 'meteo.html.twig'
